Producer_Consumer_microservice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('order.urls', namespace="order"))
]

order/urls.py
from django.urls import path

from order.views import OrderListView, NewEmployee, DeleteOrderView

app_name = "order"
urlpatterns = [
    path('', OrderListView.as_view(), name="order-list"),
    path('new-employee/', NewEmployee.as_view(), name="new-employee"),
    path('delete/<int:pk>/', DeleteOrderView.as_view(), name="order-delete"),
]

order/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Employee(AbstractUser):
    probation = models.BooleanField(default=False)
    position = models.CharField(max_length=255)

    @classmethod
    def create_employee(cls):
        max_user = cls.objects.order_by('-id').first()
        if max_user is None:
            new_username = 1
        else:
            new_username = max_user.id + 1

        new_employee = cls(
            username="user" + str(new_username),
            probation=False,
            position="cto"
        )
        new_employee.save()

        return new_employee

    def __str__(self):
        return self.username


class Order(models.Model):
    task_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name="order")

    def __str__(self):
        return self.name

order/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model

from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic, View

from Producer_Consumer_microservice.settings import BOT_TOKEN
from order.models import Order
from order.tasks import send_telegram_message

Employee = get_user_model()


class NewEmployee(View):

    def get(self, request, *args, **kwargs):
        Employee.create_employee()
        return redirect('order:order-list')


class OrderListView(generic.ListView):
    model = Order
    template_name = 'order_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.all().order_by('-task_id')


class DeleteOrderView(generic.DeleteView):
    model = Order
    success_url = reverse_lazy('order-list')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        message = (
            f"Task №-{self.object.task_id} with the title {self.object.name} " 
            f"was processed by {self.object.employee} at {datetime.datetime.now()}"
        )
        self.object.delete()
        messages.success(self.request, message)
        chat_id = self.request.COOKIES.get('chat_id')
        if chat_id and BOT_TOKEN:
            send_telegram_message.delay(chat_id, message)
        return redirect('order:order-list')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <title>{% block title %}Orders{% endblock %}</title>
</head>
<body>

  <header class="header-container">
      <i class="fab fa-telegram telegram-icon" id="telegram-icon"></i>
      <div id="telegram-input" style="display: none;">
    <input type="text" id="chat-id-input" placeholder="chat_id">
    <button id="save-button">Save</button>
    </div>

    <button class="header-button">
        <a href="{% url 'order:new-employee' %}">
            New user
        </a>

    </button>
      <script>
    const telegramIcon = document.getElementById("telegram-icon");
    const telegramInput = document.getElementById("telegram-input");
    const telegramSaveButton = document.getElementById("save-button");
    const telegramInputField = document.getElementById("chat-id-input");

    telegramIcon.addEventListener("click", () => {
        if (telegramInput.style.display === "none" || telegramInput.style.display === "") {
            telegramInput.style.display = "block";
        } else {
            telegramInput.style.display = "none";
        }
    });
    telegramSaveButton.addEventListener("click", () => {
    if (telegramInputField.value.trim().length > 0) {
        const chatIdValue = telegramInputField.value.trim();
        console.log(chatIdValue)
        const existingChatId = getCookie("chat_id");
        if (existingChatId) {
            document.cookie = "chat_id=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
        }
        document.cookie = "chat_id=" + chatIdValue + "; path=/;";
        telegramInput.style.display = "none";
    }
});
function getCookie(name) {
    const value = `; ${document.cookie}`;
    const parts = value.split(`; ${name}=`);
    if (parts.length === 2) return parts.pop().split(";").shift();
}
</script>

</header>
    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>

    </footer>

</body>
</html>
<style>
    .telegram-icon{
    position:absolute;
    top: 7px;
    left: 10px;
    font-size: 24px;
}
    #telegram-input {
    position:absolute;
    top: 5px;
    left: 40px;
    }


    .header-button {
    background-color: greenyellow;
    color: black;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
        border-radius: 20px;
    transition: background-color 0.3s;
  }

  .header-button a {
    text-decoration: none;
    color: black;
  }
  .header-button:hover {
    background-color: yellow;
}

  .header-container {
    background-color: blue;
    height: 40px;
    display: flex;
    justify-content: flex-end;
    align-items: center;
  }
    </style>

templates/order_list.html
{% extends "base.html" %}

{% block content %}

<h1 >Order list</h1>
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
<table class="table" >
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Employee</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
    {% for order in orders %}
        <tr>
            <td>{{ order.name }}</td>
            <td>{{ order.description }}</td>
            <td>{{ order.employee }}</td>
            <td><a href="{% url 'order:order-delete' order.task_id %}"><i class="fas fa-trash"></i></a></td>
        </tr>
    {% empty %}
        <p>List is empty</p>
    {% endfor %}

</table>



<style>

  table {
    border-collapse: collapse;
    width: 80%;
    border: 1px solid #ccc;
      text-align: center;
  }

  th, td {
    padding: 10px;
    border: 1px solid #ccc;
  }

  th {
    background-color: #f2f2f2;
      text-align: center;
  }

  tr:nth-child(even) {
    background-color: #f2f2f2;
  }

  tr:hover {
    background-color: #ddd;
  }

  h1 {
        text-align: center;
    }
</style>
{% endblock %}